@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.minmusxminmus.lovecraft.content.items;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;