@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.minmusxminmus.lovecraft.content.item;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;