@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.minmusxminmus.lovecraft.content.commands;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;